version: "3.7"

services:

  workspace_docker_example:
    image: workspace_docker_example
    build:
      context: .
      dockerfile: deploy/example.Dockerfile
    command: ['-tc', 'TaskTwo'] #### For my own execution
    volumes:
      - ./src:/var/task/src
      #- ~/.aws:/root/.aws
    stdin_open: true
    tty: true
